language: node_js
before_script:
  - npm install booljs@latest --no-save
node_js:
  - lts/*

deploy:
  provider: npm
  email: hola@pablodorado.com
  api_key: $NPM_API_KEY
  on:
    branch: master
    tags: true
